"""sync models

Revision ID: 31bcd72e800f
Revises: bf0209ca29a1
Create Date: 2025-11-23 22:49:22.894452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bcd72e800f'
down_revision = 'bf0209ca29a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('matiere', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.drop_column('matiere')
        batch_op.drop_column('heure')

    # ### end Alembic commands ###
