"""Ajout de la colonne ecole_id dans log

Revision ID: bf0209ca29a1
Revises: 73d068c3cd83
Create Date: 2025-10-14 02:00:21.790550
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0209ca29a1'
down_revision = '73d068c3cd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        # Ajout de la colonne ecole_id
        batch_op.add_column(sa.Column('ecole_id', sa.Integer(), nullable=True))
        # Création de la clé étrangère avec un nom explicite
        batch_op.create_foreign_key(
            'fk_log_ecole_id',  # Nom explicite obligatoire pour SQLite
            'ecole',
            ['ecole_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        # Suppression de la contrainte avec le même nom
        batch_op.drop_constraint('fk_log_ecole_id', type_='foreignkey')
        # Suppression de la colonne
        batch_op.drop_column('ecole_id')
    # ### end Alembic commands ###
